### PR TITLE
Relative hyperlinks

### PR DESCRIPTION
**Pull request by Ovski4**
The plugin works when Etherpad is installed under a subfolder or is accessed via a proxy

### CODE REVIEW

**Comment by Ovski4** [comment]
I'm afraid I'll be dead before this PR gets merged

**Comment by redhog** [comment]
Hoping merging this didn't somehow magically kill you...

**Comment by Ovski4** [comment]
😅 It would seem both of us are alive! Thanks!

**Comment by redhog** [comment]
:P

**Pull request merged**
